---
- name: Detect OS Distribution
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: Fail if unsupported distribution
      ansible.builtin.fail:
        msg: "Unsupported distribution: {{ ansible_distribution }}. Only Arch Linux and Fedora are supported."
      when: ansible_distribution not in ['Archlinux', 'Fedora']
    - name: Set distribution-specific variables
      ansible.builtin.set_fact:
        os_family: "{{ 'arch' if ansible_distribution == 'Archlinux' else 'fedora' }}"
        package_manager: "{{ 'pacman' if ansible_distribution == 'Archlinux' else 'dnf' }}"
        use_omarchy: "{{ ansible_distribution == 'Archlinux' }}"
        pnpm_packages: "{{ (pnpm_packages_common | default([])) + (pnpm_packages_arch if ansible_distribution == 'Archlinux' else pnpm_packages_fedora | default([])) }}"

- name: Create Systemd Service + Timer in User Scope.
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Get Necessary Facts Only
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "env"
          - "user_id"
    - name: Create systemd user directory
      ansible.builtin.file:
        path: "/home/{{ workstation_user }}/.config/systemd/user"
        state: directory
        mode: "0755"
        owner: "{{ workstation_user }}"
        group: "{{ workstation_user }}"
    - name: Create Ansible Pull Service
      ansible.builtin.template:
        src: ansible-pull.service.j2
        dest: "/home/{{ workstation_user }}/.config/systemd/user/ansible-pull.service"
        mode: "0644"
        owner: "{{ workstation_user }}"
        group: "{{ workstation_user }}"
    - name: Create Ansible Pull Timer
      ansible.builtin.template:
        src: ansible-pull.timer.j2
        dest: "/home/{{ workstation_user }}/.config/systemd/user/ansible-pull.timer"
        mode: "0644"
        owner: "{{ workstation_user }}"
        group: "{{ workstation_user }}"
    - name: Reload daemon
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user
    - name: Enable Ansible Pull Timer
      ansible.builtin.systemd_service:
        name: ansible-pull.timer
        state: started
        enabled: true
        scope: user
- name: Install and Update Packages
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - block:
        - name: Update Cache
          community.general.pacman:
            update_cache: true
        - name: Update Packages
          community.general.pacman:
            upgrade: true
        - name: Install Desired General Packages
          community.general.pacman:
            name: "{{ general_packages_arch }}"
      when: os_family == 'arch'
      name: Arch Linux Package Management

    - block:
        - name: Update Packages
          ansible.builtin.dnf:
            name: "*"
            state: latest
            update_cache: true
        - name: Install Desired General Packages
          ansible.builtin.dnf:
            name: "{{ general_packages_fedora }}"
            state: present
      when: os_family == 'fedora'
      name: Fedora Package Management
- name: Install and Update uv Packages
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Get list of installed uv tools
      ansible.builtin.command: uv tool list
      register: _uv_tools_list
      changed_when: false
    - name: Install uv packages
      ansible.builtin.command: "uv tool install {{ item.name }}{%if 'from' in item %} --from {{ item.from }}{% endif %}{% if item.force | default(false) %} --force{% endif %}"
      register: _uv_install
      loop: "{{ uv_packages }}"
      when: >
        item.force | default(false) or
        item.name not in _uv_tools_list.stdout
      changed_when: >
        item.force | default(false) or
        _uv_install.rc == 0
    - name: Update uv packages
      ansible.builtin.command: uv tool upgrade --all
      register: _uv_upgrade
      changed_when: '"Nothing to upgrade" not in _uv_upgrade.stderr'
- name: Install and Update Go Binaries/Tools Using `go install`
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Install go packages
      ansible.builtin.command: "go install {% if 'tags' in item %}-tags '{{ item.tags }}' {% endif %}{{ item.name }}"
      register: _go_install
      loop: "{{ go_packages }}"
      changed_when: >
        _go_install.stdout != ""
- name: Install and Update pnpm Packages
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Install pnpm packages
      community.general.pnpm:
        name: "{{ item.name }}"
        global: true
        state: latest
      register: _pnpm_install
      loop: "{{ pnpm_packages | default([]) }}"
      when: pnpm_packages | default([]) | length > 0
      changed_when: _pnpm_install.changed
- name: Create .bashrc
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Get Necessary Facts Only
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "env"
          - "user_id"
    - name: Create bashrc
      ansible.builtin.template:
        src: bashrc.j2
        dest: "/home/{{ workstation_user }}/.bashrc"
        mode: "0644"
        owner: "{{ workstation_user }}"
        group: "{{ workstation_user }}"
- name: Clone Repositories
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Get Necessary Facts Only
      ansible.builtin.setup:
        gather_subset:
          - "!all"
          - "!min"
          - "env"
          - "user_id"
    - name: Create parent directories for repositories
      file:
        path: "{{ repos_base_path }}/{{ item.remote | default(repos_default_remote) }}/{{ item.name | dirname }}"
        state: directory
        mode: '0755'
        owner: "{{ workstation_user }}"
        group: "{{ workstation_user }}"
      loop: "{{ repos }}"
      when: item.name is defined
    - name: Clone repositories
      ansible.builtin.git:
        repo: "https://{{ item.remote | default(repos_default_remote) }}/{{ item.name }}.git"
        dest: "{{ repos_base_path }}/{{ item.remote | default(repos_default_remote) }}/{{ item.name }}"
        clone: yes
        update: yes
        accept_hostkey: yes
      loop: "{{ repos }}"
      when: item.name is defined
