---

- name: Create Systemd Service + Timer in User Scope.
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: Create Ansible Pull Service
      ansible.builtin.template:
        src: ansible-pull.service.j2
        dest: "/home/{{ workstation_user }}/.config/systemd/user/ansible-pull.service"
        mode: "0644"
        owner: "{{ workstation_user }}"
        group: "{{ workstation_user }}"
    - name: Create Ansible Pull Timer
      ansible.builtin.template:
        src: ansible-pull.timer.j2
        dest: "/home/{{ workstation_user }}/.config/systemd/user/ansible-pull.timer"
        mode: "0644"
        owner: "{{ workstation_user }}"
        group: "{{ workstation_user }}"
    - name: Reload daemon
      ansible.builtin.systemd_service:
        daemon_reload: true
        scope: user
    - name: Enable Ansible Pull Timer
      ansible.builtin.systemd_service:
        name: ansible-pull.timer
        state: started
        enabled: true
        scope: user
- name: Install and Update Packages
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Update Cache
      community.general.pacman:
        update_cache: true
    - name: Update Packages
      community.general.pacman:
        upgrade: true
    - name: Install Desired General Packages
      community.general.pacman:
        name: "{{ general_packages }}"
    - name: Update uv packages
      ansible.builtin.command: uv tool upgrade --all
      register: _uv_upgrade
      changed_when: '"Nothing to upgrade" not in _uv_upgrade.stderr'
